"""Remove description from budget table

Revision ID: 49d883d1f425
Revises: 3f8726df1dd3
Create Date: 2025-10-20 22:40:54.498511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49d883d1f425'
down_revision: Union[str, Sequence[str], None] = '3f8726df1dd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budget', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget', sa.Column('description', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
